/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum StunKind {
  Msg = 0,
  Channel = 1
}
export class TurnService {
  constructor(realm: string, externals: Array<string>, observer: object)
  getProcessor(interface: string, external: string): TurnProcessor
}
export class Response {
  data: Buffer
  kind: StunKind
  relay?: string
  interface?: string
}
export class TurnProcessor {
  process(buf: Buffer, addr: string): Promise<Response | null>
}
